################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Application/User/Core \
Application/User/Startup \
Core/Src \
Drivers/CMSIS/Core/Template/ARMv8-M \
Drivers/CMSIS/Core_A/Source \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/JTest/src \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/ARMCC \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/ARMCLANG \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/GCC \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/basic_math_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/complex_math_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/controller_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/fast_math_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/filtering_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/intrinsics_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/matrix_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/statistics_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/support_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/transform_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/BasicMathFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/ComplexMathFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/ControllerFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/FastMathFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/FilteringFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/HelperFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/Intrinsics \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/MatrixFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/StatisticsFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/SupportFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/TransformFunctions \
Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example \
Drivers/CMSIS/DSP/Source/BasicMathFunctions \
Drivers/CMSIS/DSP/Source/CommonTables \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions \
Drivers/CMSIS/DSP/Source/ControllerFunctions \
Drivers/CMSIS/DSP/Source/FastMathFunctions \
Drivers/CMSIS/DSP/Source/FilteringFunctions \
Drivers/CMSIS/DSP/Source/MatrixFunctions \
Drivers/CMSIS/DSP/Source/StatisticsFunctions \
Drivers/CMSIS/DSP/Source/SupportFunctions \
Drivers/CMSIS/DSP/Source/TransformFunctions \
Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/arm \
Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc \
Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/iar \
Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates \
Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/Ref_Implementations \
Drivers/CMSIS/NN/Source/ActivationFunctions \
Drivers/CMSIS/NN/Source/ConvolutionFunctions \
Drivers/CMSIS/NN/Source/FullyConnectedFunctions \
Drivers/CMSIS/NN/Source/NNSupportFunctions \
Drivers/CMSIS/NN/Source/PoolingFunctions \
Drivers/CMSIS/NN/Source/SoftmaxFunctions \
Drivers/CMSIS/RTOS2/Source \
Drivers/CMSIS/RTOS2/Template \
Drivers/CMSIS \
Drivers/STM32F4xx_HAL_Driver/Src \
Drivers/STM32F4xx_HAL_Driver \
Drivers1/CMSIS/Core/Template/ARMv8-M \
Drivers1/CMSIS/Core_A/Source \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/Common/JTest/src \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/ARMCC \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/ARMCLANG \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/GCC \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/Common/src \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/basic_math_tests \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/complex_math_tests \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/controller_tests \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/fast_math_tests \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/filtering_tests \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/intrinsics_tests \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/matrix_tests \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/statistics_tests \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/support_tests \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/transform_tests \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/BasicMathFunctions \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/ComplexMathFunctions \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/ControllerFunctions \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/FastMathFunctions \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/FilteringFunctions \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/HelperFunctions \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/Intrinsics \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/MatrixFunctions \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/StatisticsFunctions \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/SupportFunctions \
Drivers1/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/TransformFunctions \
Drivers1/CMSIS/DSP/Examples/ARM/arm_class_marks_example \
Drivers1/CMSIS/DSP/Examples/ARM/arm_convolution_example \
Drivers1/CMSIS/DSP/Examples/ARM/arm_dotproduct_example \
Drivers1/CMSIS/DSP/Examples/ARM/arm_fft_bin_example \
Drivers1/CMSIS/DSP/Examples/ARM/arm_fir_example \
Drivers1/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example \
Drivers1/CMSIS/DSP/Examples/ARM/arm_linear_interp_example \
Drivers1/CMSIS/DSP/Examples/ARM/arm_matrix_example \
Drivers1/CMSIS/DSP/Examples/ARM/arm_signal_converge_example \
Drivers1/CMSIS/DSP/Examples/ARM/arm_sin_cos_example \
Drivers1/CMSIS/DSP/Examples/ARM/arm_variance_example \
Drivers1/CMSIS/DSP/Source/BasicMathFunctions \
Drivers1/CMSIS/DSP/Source/CommonTables \
Drivers1/CMSIS/DSP/Source/ComplexMathFunctions \
Drivers1/CMSIS/DSP/Source/ControllerFunctions \
Drivers1/CMSIS/DSP/Source/FastMathFunctions \
Drivers1/CMSIS/DSP/Source/FilteringFunctions \
Drivers1/CMSIS/DSP/Source/MatrixFunctions \
Drivers1/CMSIS/DSP/Source/StatisticsFunctions \
Drivers1/CMSIS/DSP/Source/SupportFunctions \
Drivers1/CMSIS/DSP/Source/TransformFunctions \
Drivers1/CMSIS/Device/ST/STM32F4xx/Source/Templates/arm \
Drivers1/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc \
Drivers1/CMSIS/Device/ST/STM32F4xx/Source/Templates/iar \
Drivers1/CMSIS/Device/ST/STM32F4xx/Source/Templates \
Drivers1/CMSIS/NN/NN_Lib_Tests/nn_test/Ref_Implementations \
Drivers1/CMSIS/NN/Source/ActivationFunctions \
Drivers1/CMSIS/NN/Source/ConvolutionFunctions \
Drivers1/CMSIS/NN/Source/FullyConnectedFunctions \
Drivers1/CMSIS/NN/Source/NNSupportFunctions \
Drivers1/CMSIS/NN/Source/PoolingFunctions \
Drivers1/CMSIS/NN/Source/SoftmaxFunctions \
Drivers1/CMSIS/RTOS2/Source \
Drivers1/CMSIS/RTOS2/Template \
Drivers1/STM32F4xx_HAL_Driver/Src \
MDK-ARM/CanModule22 \
MDK-ARM \

